# Generated by Django 3.2.13 on 2022-06-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211128_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='phone_number',
        ),
    ]
