# Generated by Django 3.2.5 on 2021-07-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=64)),
                ('destination', models.CharField(max_length=64)),
                ('pickTime', models.IntegerField()),
                ('finishTime', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
