# Generated by Django 3.2.5 on 2021-08-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_edges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edges',
            new_name='Edge',
        ),
    ]
