# Generated by Django 3.2.5 on 2021-08-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_edges_edge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='finishTime',
        ),
    ]
