# Generated by Django 3.2.5 on 2021-11-22 02:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210804_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ride',
            name='username',
            field=models.CharField(default='', max_length=64),
        ),
    ]
