# Generated by Django 3.2.5 on 2021-11-29 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211122_0201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='username',
            new_name='rider_name',
        ),
    ]
