# Generated by Django 3.2.5 on 2021-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20211129_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='duration',
            field=models.CharField(default='', max_length=30),
        ),
    ]
