# Generated by Django 3.2.13 on 2022-07-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_duration_ride_trip_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_status',
            field=models.CharField(default='pending', max_length=30),
        ),
    ]
