# Generated by Django 3.2.13 on 2022-07-18 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_ride_ride_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='needs',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='ride',
            name='roundtrip',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rtime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='ride',
            name='share',
            field=models.CharField(default='', max_length=30),
        ),
    ]
